Repository narvis2/Reservation-Api-Server, pull requests merged in 2023-08, with the labels that each got.

#27 🦋 FCM 기능 구현 🦋
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/thepan/reservationapiserver/InitDB.kt
  src/main/kotlin/com/thepan/reservationapiserver/config/firebase/FCMConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/fcm/dto/FCMNotificationRequest.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/fcm/enum/NotiType.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/fcm/service/FCMNotificationService.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/mapper/OjbectMapper.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/entity/Member.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/ReservationService.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/dto/ReservationCreateRequest.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/entity/Reservation.kt
  src/main/kotlin/com/thepan/reservationapiserver/utils/Constants.kt
Labels: add

#28 앱 실행시 띄울 공지사항 더미 데이터 추가
  src/main/kotlin/com/thepan/reservationapiserver/InitDB.kt
Labels: test

#29 🦋 Member Entity 에 FcmToken 을 추가하는 API 추가 🦋
  src/main/kotlin/com/thepan/reservationapiserver/controller/MemberApiController.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/dto/MemberUpdateFcmTokenRequest.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/service/MemberService.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/sign/dto/SignOutRequest.kt
Labels: add

#30 🦋 로그아웃 API 인가 적용 및 로직 수정 🦋
  src/main/kotlin/com/thepan/reservationapiserver/config/SecurityConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/controller/SignApiController.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/sign/dto/SignOutRequest.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/sign/service/SignService.kt
Labels: modify

#31 🦋 /member/fcm-token API 용도 수정 🦋
  src/main/kotlin/com/thepan/reservationapiserver/controller/MemberApiController.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/dto/MemberUpdateFcmTokenRequest.kt
Labels: modify

#32 🦋 FcmPush 활성화/비활성화 기능 구현 🦋
  src/main/kotlin/com/thepan/reservationapiserver/InitDB.kt
  src/main/kotlin/com/thepan/reservationapiserver/controller/MemberApiController.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/fcm/service/FCMNotificationService.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/mapper/OjbectMapper.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/dto/MemberUpdateEnablePushRequest.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/dto/MyMemberInfoResponse.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/entity/Member.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/member/service/MemberService.kt
Labels: add

#33 Maria db setting
  build.gradle.kts
  src/main/kotlin/com/thepan/reservationapiserver/InitDB.kt
  src/main/kotlin/com/thepan/reservationapiserver/config/RedisRepositoryConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/config/SecurityConfig.kt
  src/main/resources/application.yml
Labels: modify

#35 🦋예약 목록 전체 조회 PageNation 및 필터 적용 🦋
  build.gradle.kts
  src/main/kotlin/com/thepan/reservationapiserver/config/QuerydslConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/config/RedisRepositoryConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/config/SecurityConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/controller/ReservationApiController.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/mapper/OjbectMapper.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/ReservationService.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/dto/enum/ReservationFilterType.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/dto/page/ReservationConditionResponse.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/dto/page/ReservationListResponse.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/dto/page/ReservationReadConditionRequest.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/repository/CustomReservationRepository.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/repository/CustomReservationRepositoryImpl.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/repository/ReservationRepository.kt
  src/main/resources/application.yml
Labels: add

#36 🦋 개발기 🦋
  build.gradle.kts
  src/main/kotlin/com/thepan/reservationapiserver/InitDB.kt
  src/main/kotlin/com/thepan/reservationapiserver/config/RedisRepositoryConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/config/SecurityConfig.kt
  src/main/resources/application.yml
Labels: DEV

#37 🦋 예약 정보 상세보기 API 추가 🦋
  src/main/kotlin/com/thepan/reservationapiserver/config/SecurityConfig.kt
  src/main/kotlin/com/thepan/reservationapiserver/controller/ReservationApiController.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/mapper/OjbectMapper.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/ReservationService.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/dto/ReservationDetailByUserRequest.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/dto/ReservationDetailResponse.kt
  src/main/kotlin/com/thepan/reservationapiserver/domain/reservation/repository/ReservationRepository.kt
Labels: add
